# Generated by Django 3.1 on 2020-08-31 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200831_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 14, 48, 11, 376940, tzinfo=utc)),
        ),
    ]
